name: .NET Core Deploy APIS 

on:
  push:
    branches: 
      - master
    paths: 
      - '**apis/poi/**'
       
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v2
          
      - uses: azure/docker-login@v1
        with:
          login-server: openhackijm6tyx0acr.azurecr.io
          username: ${{secrets.ACRUSER}}
          password: ${{secrets.ACRPWD}}

#      - name: build and push
#        run: |
#          docker build apis/poi/web -t openhackijm6tyx0acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}
#          docker push openhackijm6tyx0acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}
    
      - name: Set Web App ACR authentication
        uses: Azure/appservice-settings@v1
        with:
         app-name: 'openhackijm6tyx0poi'
         app-settings-json: |
           [
               {
                   "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                   "value": "${{ secrets.ACRPWD }}",
                   "slotSetting": false
               },
               {
                   "name": "DOCKER_REGISTRY_SERVER_URL",
                   "value": "https://openhackijm6tyx0acr.azurecr.io",
                   "slotSetting": false
               },
               {
                   "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                   "value": "${{ secrets.ACRUSER  }}",
                   "slotSetting": false
               },
               {
                   "name": "WEBSITES_WEB_CONTAINER_NAME",
                   "value": "devopsoh/api-poi:e02eb32de4efde4a9891eeed1e1624fe6dbbb2bd",
                   "slotSetting": false
               }  
           ]


      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'openhackijm6tyx0poi'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'openhackijm6tyx0acr.azurecr.io/devopsoh/api-poi:e02eb32de4efde4a9891eeed1e1624fe6dbbb2bd'
        
      - name: The job has failed
        uses: stefanstranger/azuredevops-bug-action@1.1
        if: failure()
        with:
            OrganizationName: "brvuong0311"
            PAT: "PAT"
            ProjectName: "OpenHackDevOps"
            AreaPath: "OpenHackDevOps"
            IterationPath: "OpenHackDevOps\\Sprint 1"
            GithubToken: "GithubToken"
            WorkflowFileName: "cd-apis-poi.yaml"
        env:
            PAT: ${{secrets.PAT}}
            GithubToken: ${{secrets.githubtoken}}
    
