name: CI-API-TRIPS

on:
  pull_request:    
    paths: 
      - '**apis/trips/**'
       
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with: 
        dotnet-version: 2.1
    - name: Install dependencies
      run: dotnet restore apis/trips
    - name: Build
      run: dotnet build apis/trips --configuration Release --no-restore
    - name: Test
      run: dotnet test apis/trips/tests 

    - name: The job has failed
      uses: stefanstranger/azuredevops-bug-action@1.1
      if: failure()
      with:
          OrganizationName: "brvuong0311"
          PAT: "PAT"
          ProjectName: "OpenHackDevOps"
          AreaPath: "OpenHackDevOps"
          IterationPath: "OpenHackDevOps\\Sprint 1"
          GithubToken: "GithubToken"
          WorkflowFileName: "ci-api-trips.yaml"
      env:
          PAT: ${{secrets.PAT}}
          GithubToken: ${{secrets.githubtoken}}
