name: .NET Core

on:
  pull_request:
    branches: 
      - master
    paths: 
      - '**apis/poi/**'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Run a multi-line script
      shell: bashx
      run: echo "test"  

