name: .NET Core

on:
  push:
    branches: 
      - master
    paths: 
      - '**apis/poi/**'
       
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2.1
      with: 
        dotnet-version: 2.1
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build apis/poi/web --configuration Release --no-restore
    - name: Test
      run: dotnet test apis/poi/tests/UnitTests/*.csproj --no-restore --verbosity normal  

    - name: The job has failed
      uses: stefanstranger/azuredevops-bug-action@1.1
      if: failure()
      with:
          OrganizationName: "brvuong0311"
          PAT: "PAT"
          ProjectName: "OpenHackDevOps"
          AreaPath: "OpenHackDevOps"
          IterationPath: "OpenHackDevOps\\Sprint 1"
          GithubToken: "GithubToken"
          WorkflowFileName: "dotnet-core.yml"
      env:
          PAT: ${{secrets.PAT}}
          GithubToken: ${{secrets.githubtoken}}
